### ISSUE TITLE
USER STORY: Hide identity

### ISSUE THREAD

**Issue by sharondrinkwaard** [sharondrinkwaard/love-running-project#2]
In order to **provide anonymous feedback ** as a **user**, I can **choose to hide my identity in the poll response**

## Acceptance Criteria
* Checkbox 
* Text under checkbox: "Hide my name"
* Hide first and last name of user when checkbox is clicked / replace names with anonymous

## Tasks
- [ ] Update the view: the poll desing (HTML, CSS) to include the checkbox and to show the name of the submitter
- [ ] Create a new field to track the username
- [ ] Update the controller function
- [ ] Test functionality
